<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
<head>
    <title>EMQDesenv - Aplicações</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="https://fonts.googleapis.com/css?family=Lovers+Quarrel|Miltonian+Tattoo|Sriracha" rel="stylesheet" /> 
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Acme|Actor|Akronim|Allura|Antic+Slab|Architects+Daughter|Audiowide|Bad+Script|BioRhyme|Boogaloo|Calligraffitti|Ceviche+One|Chewy|Comfortaa|Coming+Soon|Cookie|Courgette|Crafty+Girls|Damion|Dancing+Script|Fascinate|Fontdiner+Swanky|Freckle+Face|Fredericka+the+Great|Gloria+Hallelujah|Gochi+Hand|Grand+Hotel|Great+Vibes|Handlee|Indie+Flower|Jacques+Francois+Shadow|Josefin+Slab|Kalam|Kaushan+Script|Leckerli+One|Lobster|Lobster+Two|Marck+Script|Marko+One|Meddon|Monsieur+La+Doulaise|Nosifer|Pacifico|Patrick+Hand|Permanent+Marker|Playball|Risque|Rock+Salt|Ruda|Ruslan+Display|Russo+One|Sacramento|Satisfy|Schoolbell|Shadows+Into+Light|Shadows+Into+Light+Two|Shrikhand|Stalemate|Sunshiney|VT323|Yellowtail" rel="stylesheet"> 
    <link rel="shortcut icon" href="emqdesenv.ico" type="image/x-icon" />
    <meta name="description" content="emqdesenv - Aplicações" />
    <meta name="keywords" content="sistemas, PHP" />
    <meta name="author" content="Edmilson Messias Quintino" />

    <!-- Definindo o tamanho da tela --> 
    <meta name="viewport" content="width=device-width">  
    <link rel="stylesheet" href="css/layout.css" type="text/css" media='screen'/>    
    <link rel="stylesheet" href="css/menu.css" type="text/css" />   
    <link rel="stylesheet" href="css/tempo.css" type="text/css" media='screen'/>   
    <!--<link rel="stylesheet" href="css/mobile.css" media="(max-width: 939px)" />-->
   <link rel="stylesheet" href="js/slide.js" />
    <!--<link rel="stylesheet" href="css/mobile2.css" media="(max-width: 939px)"> -->
   <script type="text/javascript" src="../web/js/js.js"></script>
   <script type="text/javascript" src="../web/js/missao.js"></script>
   <script type="text/javascript" src="../web/js/cadastro.js"></script>
   <script src="../web/js/upload.js" type="text/javascript"></script>
   <script src='../web/js/jquery-3.2.1.min.js' type='text/javascript'></script>
   <script type="text/javascript" src="../web/js/jquery.js"></script>
   <script type="text/javascript" src="../web/js/jquery.cookie.js"></script>
   
   <!--<script type="text/javascript" src="../web/js/jquery-pack.js"></script>
   <script type="text/javascript" src="../web/js/jquery.imgareaselect.min.js"></script>-->
   
</head>
    <body onload="startSlideShow()" id=seletor>     
        <!-- header -->
         <div id="cabecalho">
            <span class="cor_1" id="logo">Jogo de RPG</span>
                  <?php 
                    include '../dao/dao.php';
                    include '../dao/ModelSearchCriteria.php';
                    
                    @$login = strtoupper($_COOKIE['login']);
                    $dao = new dao();
                    $search = new ModelSearchCriteria();
                    $search->settabela('personagem');
                    $search->setjogador($login);
                    $dados = $dao->encontre($search);
                    
                    if($login<>'MESTRE'){ 
                        $menu=array('home'=>'Home','cadastro'=>'Cadastro de Personagem','lista'=>'Personagens'); 
                        if(@!$dados){
                           $menu=array('home'=>'Home','cadastro'=>'Cadastro de Personagem');
                        }
                    }else{
                        $menu=array('home'=>'Home','cadastro'=>'Cadastro de Personagem','lista'=>'Personagens','viloes'=>'Vilões','missao'=>'Missão');  
                        echo "<div class='tempo'>";
                           echo '<iframe scrolling="no" frameborder=0 src="tempo.php"></iframe>';
                        echo '</div>';                     
                    }
                    
                    foreach($dados as $dado){
                        $personagem = $dado->getpersonagem();
                        $jogador = $dado->getjogador();
                    } 
                    if(@!$personagem){
                        $personagem = null;
                    }
                    
            echo '<div id="menu" >';
                    echo '<ul class="menu">';  
                    if(!isset($jogador)){
                       $jogador=null;
                    }
                        foreach($menu as $key => $item){
                           if($item == 'Cadastro de Personagem'){
                              echo '<li><a href="'.Utils::createLink('cadastro',array('act'=>'cad','pag'=>0)).'" >'.$item.'</a></li>';
                           }elseif($item == 'Personagens'){
                               if($login<>'MESTRE'){
                                    echo '<li><a href="'.Utils::createLink('cadastro',array('act'=>'lista','pag'=>0)).'" >'.$item.'</a>';
                               }else{
                                    echo '<li>'.$item;
                                        echo '<ul class="sub-menu">';
                                           echo '<a href="'.Utils::createLink('cadastro',array('act'=>'lista','jogador'=>''.$jogador.'','pag'=>0)).'" ><li>Jogadores</li></a>';
                                           echo '<a href="'.Utils::createLink('cadastro',array('act'=>'lista','jogador'=>'DOMESTRE','pag'=>0)).'" ><li>do Mestre</li></a>';
                                        echo '</ul>';
                               }
                                echo '</li>';
                           }elseif($item == 'Missão'){
                              echo '<li>'.$item.'';
                                echo '<ul class="sub-menu">';
                                    echo '<a href="'.Utils::createLink($key,array('personagem'=>$personagem,'act'=>'nova')).'" ><li>Nova</li></a>';
                                    echo '<a href="'.Utils::createLink($key,array('personagem'=>$personagem,'act'=>'inicia')).'" ><li>Iniciar</li></a>';
                                echo '</ul>';
                              echo '</li>';
                           }elseif($item == 'Vilões'){
                              echo '<li>'.$item.'';
                                echo '<ul class="sub-menu">';
                                    echo '<a href="'.Utils::createLink($key,array('act'=>'novo')).'" ><li>Novo</li></a>';
                                    echo '<a href="'.Utils::createLink($key,array('act'=>'lista')).'" ><li>Lista</li></a>';
                                echo '</ul>';
                              echo '</li>';
                           }else{
                              echo '<li><a href="'.Utils::createLink($key).'" >'.$item.'</a></li>';
                           }
                        }
                     echo '</ul>';
                    if(@$login){
                        echo '<span id=sair>Jogador '.$login.' <img height=25px title="Sair" src="../web/imagens/sair.png" /></span>';
                    }
                  ?>
            </div>
         </div>
         <div class="col-1"></div>
         <div class="col-2">
            <div class="indent">
               <?php if ($flashes): ?>
                  <ul id="flashes">
                     <?php foreach ($flashes as $flash): ?>
                        <li><?php echo $flash; ?></li>
                     <?php endforeach; ?>
                  </ul>
               <?php endif; ?>
               <?php require $template; ?>
            </div>
         </div>
</body>
</html>