<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
<head>
    <title>EMQDesenv - Aplicações</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="https://fonts.googleapis.com/css?family=Lovers+Quarrel|Miltonian+Tattoo|Sriracha" rel="stylesheet" /> 
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Acme|Actor|Akronim|Allura|Antic+Slab|Architects+Daughter|Audiowide|Bad+Script|BioRhyme|Boogaloo|Calligraffitti|Ceviche+One|Chewy|Comfortaa|Coming+Soon|Cookie|Courgette|Crafty+Girls|Damion|Dancing+Script|Fascinate|Fontdiner+Swanky|Freckle+Face|Fredericka+the+Great|Gloria+Hallelujah|Gochi+Hand|Grand+Hotel|Great+Vibes|Handlee|Indie+Flower|Jacques+Francois+Shadow|Josefin+Slab|Kalam|Kaushan+Script|Leckerli+One|Lobster|Lobster+Two|Marck+Script|Marko+One|Meddon|Monsieur+La+Doulaise|Nosifer|Pacifico|Patrick+Hand|Permanent+Marker|Playball|Risque|Rock+Salt|Ruda|Ruslan+Display|Russo+One|Sacramento|Satisfy|Schoolbell|Shadows+Into+Light|Shadows+Into+Light+Two|Shrikhand|Stalemate|Sunshiney|VT323|Yellowtail" rel="stylesheet"> 
    <link rel="shortcut icon" href="emqdesenv.ico" type="image/x-icon" />
    <meta name="description" content="emqdesenv - Aplicações" />
    <meta name="keywords" content="sistemas, PHP" />
    <meta name="author" content="Edmilson Messias Quintino" />

    <!-- Definindo o tamanho da tela --> 
    <meta name="viewport" content="width=device-width">  
    <link rel="stylesheet" href="css/layout.css" type="text/css" media='screen'/>   
    <link rel="stylesheet" href="css/tempo.css" type="text/css" media='screen'/>   
    <link rel="stylesheet" href="css/mobile.css" media="(max-width: 939px)" />
    <link rel="stylesheet" href="js/slide.js" />
    <!--<link rel="stylesheet" href="css/mobile2.css" media="(max-width: 939px)"> -->
    
    
        <script type="text/javascript">// <![CDATA[
    var imageCount = 0;
    var currentImage = 0;
    var images = new Array();
     
    images[0] = 'imagens/1.jpg';
    images[1] = 'imagens/2.jpg';
    images[2] = 'imagens/3.jpg';
    images[3] = 'imagens/4.jpg';
    images[4] = 'imagens/5.jpg';
    images[5] = 'imagens/6.jpg';
    images[6] = 'imagens/7.jpg';
    images[7] = 'imagens/8.jpg';
    images[8] = 'imagens/9.jpg';
    images[9] = 'imagens/10.jpg';
    images[10] = 'imagens/11.jpg';
     
    var preLoadImages = new Array();
    for (var i = 0; i < images.length; i++)
    {
       if (images[i] == "")
          break;
     
       preLoadImages[i] = new Image();
       preLoadImages[i].src = images[i];
       imageCount++;
    }
    function troca(){
	if (id<imgs.length-1){
            id++;	
	}else{
            id=0
	}
	$("#box").fadeOut(500);
	setTimeout("$('#box').html('<img src=\""+imgs[id]+"\" width=\"100%\" height=\"100%\" />');$('#box').fadeIn(500);",500);
    }
     
    function startSlideShow(){
        if (document.body && imageCount > 0){
            var objeto = "url("+images[currentImage]+")";
            
            
            document.body.style.backgroundImage = objeto;    
            document.body.style.backgroundAttachment = "fixed";
            document.body.style.backgroundRepeat = "repeat";
            document.body.style.backgroundPosition = "left top";
     
            currentImage = currentImage + 1;
            if (currentImage > (imageCount-1)){ 
                currentImage = 0;
            } 
            /*var segundos = 10; //Segundos entre cada imagem
            setInterval('startSlideShow()',segundos*1000);*/       
            setTimeout('startSlideShow()', 3600);          
        }
    }
    function fadeIn(element,time){
        processa(element,time,0,100);
    }
    function sair(personagem){
        var personagem;
        document.cookie = "login=; path=/";
        document.cookie = "senha=; path=/";
        window.location.replace('../web/sair.php?personagem='+personagem+'');
    }
    // ]]></script>
</head>
    <body onload="startSlideShow()">     
        <!-- header -->
         <div id="cabecalho">
            <span class="cor_1" id="logo">Jogo de RPG</span>
                  <?php 
                    include '../dao/dao.php';
                    include '../dao/ModelSearchCriteria.php';
                    @$login = strtoupper($_COOKIE['login']);
                    $dao = new dao();
                    $search = new ModelSearchCriteria();
                    $search->settabela('personagem');
                    $search->setjogador($login);
                    $dados = $dao->encontre($search);
                    if($login<>'MESTRE'){
                        $menu=array('home'=>'Home','cadastro'=>'Cadastro de Personagem','lista'=>'Personagens','missao'=>'Missão'); 
                        if(@!$dados){
                           $menu=array('home'=>'Home','cadastro'=>'Cadastro de Personagem');
                        }
                    }else{
                        $menu=array('home'=>'Home','cadastro'=>'Cadastro de Personagem','lista'=>'Personagens','dado'=>'Rolagem de Dado');                        
                    }
                    
                    foreach($dados as $dado){
                        $personagem = $dado->getpersonagem();
                        if($dado->getemMissao()==1){
                            //echo 'Personagem '.$item->getpersonagem().' está em missão.';
                            echo "<div class='tempo'>";
                                echo '<iframe scrolling="no" frameborder=0 src="tempo.php"></iframe>';
                            echo '</div>';
                            //$personagem = $dado->getpersonagem();
                        }
                    } 
                    if(@!$personagem){
                        $personagem = null;
                    }
                    
            echo '<div id="menu" >';
                    echo '<ul>';                                             
                        foreach($menu as $key => $item){
                           if($item == 'Cadastro de Personagem'){
                              echo '<li><a href="'.Utils::createLink('cadastro',array('act'=>'cad','pag'=>0)).'" ><span class="bnt">'.$item.'</span></a></li>';
                           }elseif($item == 'Personagens'){
                              echo '<li><a href="'.Utils::createLink('cadastro',array('act'=>'lista','pag'=>0)).'" ><span class="bnt">'.$item.'</span></a></li>';
                           }elseif($item == 'Missão'){
                              echo '<li><a href="'.Utils::createLink($key,array('personagem'=>$personagem)).'" ><span class="bnt">'.$item.'</span></a></li>';
                           }else{
                              echo '<li><a href="'.Utils::createLink($key).'" ><span class="bnt">'.$item.'</span></a></li>';
                           }
                        }
                     echo '</ul>';
                    if(@$login){
                        echo '<div class=saudacao1>Jogador '.$login.' <img onclick=sair("'.$personagem.'") height=25px title="Sair" src="../web/imagens/sair.png" /></div>';
                    }
                  ?>
            </div>
         </div>
         <div class="col-1"></div>
         <div class="col-2">
            <div class="indent">
               <?php if ($flashes): ?>
                  <ul id="flashes">
                     <?php foreach ($flashes as $flash): ?>
                        <li><?php echo $flash; ?></li>
                     <?php endforeach; ?>
                  </ul>
               <?php endif; ?>
               <?php require $template; ?>
            </div>
         </div>
</body>
</html>