<?php
@$act=$_GET['act'];
@$dado=$_POST['dado'];
if(@!$dado){
  @$dado=$_GET['dado'];
}
@$rolar=$_POST['rolar'];
 function redirecionar($tempo,$url, $mensagem){
  header("Refresh: $tempo; url=$url");
  echo "<div class=carregando>";
  echo '<center>'.$mensagem.  '</center><br/>';
  echo '<center><img src="imagens/dado.gif" alt="" /><br/><br/><tt><i>girando o dado...</i></tt></center>';
  echo "</div>";
 }
 echo '<div class="conteudo">';
 echo '<br><br><br>';
 ?>
<center>
    <form action="index.php?pagina=dado2&act=1" method="post">
        <!--<select name="dado" required="">
            <option></option>
            <option value="6">D6</option>
            <option value="20">D20</option>
        </select> -->
        <legenda class="t_dado">Escolha o dado abaixo</legenda>
        <br><br>
        <img height=60px src='../web/imagens/d6.png'>
        <input type='radio' name='dado' value='6' required="">
        <img height=60px src='../web/imagens/d20.png'>
        <input type='radio' name='dado' value='20'>
        <input type="hidden" name="rolar" value="1">
        <br><br>
        <input class='rolar rolar-red' type="submit" value="ok">
    </form>
</center>
<br><br>
 <?php
 if($rolar){
	redirecionar('1','index.php?pagina=dado2&dado='.$dado.'&abrir=1','AGUARDE');
 }elseif($dado){
	$dado_ = rand(1,$dado);
        echo '<center>';
           echo "Você rolou o dado e...<br />";
           echo "Tirou um <span class='resultado'>$dado_</span>";
        echo '</center>';
 }
 echo '</div>';
?>