<script>
  function rolaDado($rdado,y){
    var x = $rdado;
    document.getElementById('dado'+y).innerHTML = '<img height=60px src='+x+' />';
  }
</script>
<?php
@$act=$_GET['act'];
@$dado=$_POST['dado'];
if(@!$dado){
  @$dado=$_GET['dado'];
}
@$rolar=$_POST['rolar'];
 function redirecionar($tempo,$url, $mensagem, $dado){
  header("Refresh: $tempo; url=$url");
  echo '<script>rolaDado(\'imagens/dado/rd'.$dado.'.gif\','.$dado.')</script>';
  echo "<div class=carregando>";
  echo '<center class=msg>'.$mensagem.  '</center><br/>';
  //echo '<center><img height=70px src="imagens/dado/rd'.$dado.'.gif" alt="" /><br/><br/></center>';
  echo "</div>";
 }
 echo '<div class="conteudo">';
 echo '<br><br><br>';
 ?>
<center>
    <form action="index.php?pagina=dado2&act=1" method="post">
        <!--<select name="dado" required="">
            <option></option>
            <option value="6">D6</option>
            <option value="20">D20</option>
        </select> -->
        <legenda class="t_dado">Escolha o dado abaixo</legenda>
        <br><br>  
        <span id='dado6'><img height=56px title='Dado de 6 lados' src='../web/imagens/d6.png'></span>
        <input type='radio' name='dado' value='6' required="">
        <span id='dado20'><img height=60px title='Dado de 20 lados' src='../web/imagens/d20.png'></span>
        <input type='radio' name='dado' value='20'>
        <input type="hidden" name="rolar" value="1">
        <br><br>
        <input class='rolar rolar-red' type="submit" value="ok">
    </form>
</center>
<br><br>
 <?php
        echo '<div class=resultado>';
 if($rolar){
	redirecionar('1','index.php?pagina=dado2&dado='.$dado.'&abrir=1','Aguarde...',$dado);
 }elseif($dado){
	$dado_ = rand(1,$dado);
           //echo "Você rolou o dado e...<br />";
           echo "Você tirou<br><span>$dado_</span>";
           //echo '<script>document.write(processa('.$dado_.',1,100,1));</script>';
        echo '</div>';
 }
 echo '</div>';
?>