<script>
  function rolaDado($rdado,y){
    var x = $rdado;
    mostrarDado();
    document.getElementById('dado'+y).innerHTML = '<img height=60px src='+x+' />';
  }
   function mostrarDado(){
    var dado = getRadioValor('dado');
    document.getElementById('resultado').innerHTML = '';
    //alert(dado);
    //document.write('<img height=60px src="imagens/dado/rd'+dado+'.gif" />');
    if(dado == '6x2'){
       document.getElementById('dado'+dado).innerHTML = '<img height=60px src="imagens/dado/rd'+dado+'.gif" />';
       document.getElementById('dado2'+dado).innerHTML = '<img height=60px src="imagens/dado/rd'+dado+'.gif" />';
    }else{
       document.getElementById('dado'+dado).innerHTML = '<img height=60px src="imagens/dado/rd'+dado+'.gif" />';
   }
  //alert('O valor selecionado é '+ getRadioValor('dado'));
  //,'.$dado.'
 }
  
 function getRadioValor(name){
  var rads = document.getElementsByName(name);
   
  for(var i = 0; i < rads.length; i++){
   if(rads[i].checked){
    return rads[i].value;
   } 
  }  
  return null;
 }
  /*botao.addEventListener('mousedown', function (event) {
     x += 1;
});
  function teste(){
  document.getElementById("test").addEventListener("click", function( event ) {
    // mostra o contador de cliques dentro da div clicada
    event.target.innerHTML = "Total de cliques: " + event.detail;
  }, false);
 }
 */
</script>
<?php
@$act=$_GET['act'];
@$dado=$_POST['dado'];
if(@!$dado){
  @$dado=$_GET['dado'];
}
@$rolar=$_POST['rolar'];
 function redirecionar($tempo,$url, $mensagem, $dado){
  //header("Refresh: $tempo; url=$url");
  echo '<script>rolaDado(\'imagens/dado/rd'.$dado.'.gif\','.$dado.')</script>';
  echo "<div class=carregando>";
  echo '<center class=msg>'.$mensagem.  '</center><br/>';
  //echo '<center><img height=70px src="imagens/dado/rd'.$dado.'.gif" alt="" /><br/><br/></center>';
  echo "</div>";
 }
 echo '<div class="conteudo">';
 echo '<br><br><br>';
 ?>
<center>
    <form action="index.php?pagina=dado&act=1" method="post">
        <!--<select name="dado" required="">
            <option></option>
            <option value="6">D6</option>
            <option value="20">D20</option>
        </select> -->
        <legenda class="t_dado">Escolha o dado abaixo</legenda>
        <br><br>  
        <span id='dado6'><img height=56px title='Dado de 6 lados' src='../web/imagens/d6.png'></span>
        <input type='radio' id="dado" name='dado' value='6' required="">  
        <span id="dado6x2"><img height=56px title='Dado de 6 lados' src='../web/imagens/d6.png'></span><span id='dado26x2'><img height=56px title='Dado de 6 lados' src='../web/imagens/d6.png'></span>
        <input type='radio' id="dadox2" name='dado' value='6x2' required="">
        <span id='dado20'><img height=60px title='Dado de 20 lados' src='../web/imagens/d20.png'></span>
        <input type='radio' id="dado2" name='dado' value='20'>
        <input type="hidden" name="rolar" value="1">
        <br><br>
        <!--<input class='rolar rolar-red' type="submit" value="ok">-->
        <button title="Aperte e segure para girar o dado." class='rolar rolar-red' onmousedown="mostrarDado()"; >Segure para girar</button> 
        <!--rolaDado('imagens/dado/rd20.gif','20')-->
        
        <!--<button class='rolar rolar-red' onmousedown/onmouseup="alert('vou parar')"; >Para</button> -->
    </form>
</center>
<br><br>
 <?php
        echo '<div id=resultado class=resultado>';
 if($rolar){
        //echo $dado;
        if($dado == '6x2'){
           $dado_ = rand(1,6)+rand(1,6);
        }else{
           $dado_ = rand(1,$dado);
        }
           //echo "Você rolou o dado e...<br />";
           echo "Você tirou<br><span>$dado_</span>";
	//redirecionar('1','index.php?pagina=dado&dado='.$dado.'&abrir=1','Aguarde...',$dado);
 }/*elseif($dado){
	$dado_ = rand(1,$dado);
           //echo "Você rolou o dado e...<br />";
           echo "Você tirou<br><span>$dado_</span>";
           //echo '<script>document.write(processa('.$dado_.',1,100,1));</script>';
        echo '</div>';
 }*/
 echo '</div>';
?>