<style>
    #rodape{
        visibility: hidden;
    }
</style>
<?php 
    $variaveis=array('JOGADOR'=>'jogador','PERSONAGEM'=>'personagem','RAÇA'=>'raca','CLASSE'=>'classe','TENDÊNCIA1'=>'tendencia1','TENDÊNCIA2'=>'tendencia2','SEXO'=>'sexo');
    @$personagem=$_GET['personagem'];
    if(!$personagem){
      $personagem='nulo';
    }
?>
<div  class="conteudo" >
    <div class="jogador">
               <?php 
                  $dao=new Dao();
                  $search=new ModelSearchCriteria();
                  $search->settabela('personagem');
                  $search->setpersonagem($personagem);
                  $lista=$dao->encontre($search);
                  //print_r($lista);die;
                  @$level=$_GET['level'];
                  if(!$level){
                     $level=1; 
                  }
                  $titulos=array('PERSONAGEM','RAÇA','CLASSE','TENDÊNCIA1','TENDÊNCIA2');
        echo '<br><br><br>';
        echo '<fieldset class="ficha"><legend>FICHA DE PERSONAGEM &nbsp&nbsp LEVEL '.$level.'</legend>';
           echo '<table cellspacing=0 border=1 class=tabelaFicha>';
              if(!$lista){
                die('Personagem Inexistente');
              }
                  foreach($lista as $keys => $item){
                     echo '<tr><td class=nomes>'.$titulos[0].'</td><td class=nomes2>'.$item->getpersonagem().'</td></tr>';
                     echo '<tr><td class=nomes>'.$titulos[1].'</td><td class=nomes2>'.$item->getraca().'</td></tr>';
                     echo '<tr><td class=nomes>'.$titulos[2].'</td><td class=nomes2>'.$item->getclasse().'</td></tr>';
                     echo '<tr><td class=nomes>'.$titulos[3].'</td><td class=nomes2>'.$item->gettendencia1().'</td></tr>';
                     echo '<tr><td class=nomes>'.$titulos[4].'</td><td class=nomes2>'.$item->gettendencia2().'</td></tr>';
                     echo '<div class=motivacao>';
                       echo '<span class=fichaTitulo>Motivação</span>';
                       echo '<p class=motivacaoTexto>'.$item->getmotivacao().'</p>';
                     echo '</div>';
                     //echo '<tr><td colspan=2 class=divisao>Características</td><tr>';
                     echo '<div id="aqui" class="raca">Bem-vindo <span class=motivacaoJogador>'.strtoupper($item->getjogador()).'</span>  <br><img height=240px src="../web/imagens/personagens/'.$item->getraca().'/'.$item->getraca().'.png" /></div>';
                     echo '<div class=historia>';                    
                       echo '<span class=hTitulo>Uma breve história</span>'; 
                       echo '<span class=hTexto >
                        <p>Tenho '.$item->getidade().' anos, '.$item->getaltura().'m de altura, peso '.$item->getpeso().'Kg, nasci na cidade de '.$item->getcidade().'.</p><p>'.$item->getbreveHistoria().'</p></span>';
                     echo '</div>';
                  //}
                  echo '<div class=equipamento>';        
                       echo '<span>Equipamento</span>';
                       echo '<span class=linhas><hr><hr><hr><hr><hr><hr><hr><hr><hr></span>';
                  echo '</div>';
                       echo '</table>';
                       echo '<from action="#" method=POST>';
                       echo '<table class=atributo>';
                       echo '<caption class=fichaTitulo>Atributos</caption>';
                       $tCaracteristicas=array('F'=>'Força','A'=>'Agilidade','I'=>'Inteligência','V'=>'Vontade','PV'=>'Pontos de Vida','PM'=>'Pontos de Magia','PE'=>'Pontos de Experiência');
                       foreach($tCaracteristicas as $key => $item_){
                         if($item_[0] == 'P'){
                           $item_=(explode(' ',$item_));
                           echo '<tr><td><span class="destaque atr">'.$item_[0][0].'</span>'.substr($item_[0], 1).' '.$item_[1].'<span class="destaque atr"> '.$item_[2][0].'</span>'.substr($item_[2], 1).'</td><td><input type=text name='.$key.' maxlength = "4" size=2></td></tr>';
                         }else{
                          echo '<tr><td><span class="destaque atr">'.$item_[0].'</span>'. substr($item_, 1).'</td><td><input type=text name='.$key.' maxlength = "4" size=2></td></tr>';
                         }
                       }
                       echo '</table>';
                       echo '<br>';
                       echo '<div class=vantagens>';
                       echo '<caption class=fichaTitulo>Habilidades</caption>';
					   echo '<br>';
					   $hab=explode('/',$item->gethabilidade());
					   echo '<ul>';
						   echo '<li><img height=10px src="..\web\imagens\circulo.gif"> '.str_replace('_',' ',substr($hab[0],4)).'</li><br>';
						   echo '<li><img height=10px src="..\web\imagens\circulo.gif"> '.str_replace('_',' ',substr($hab[1],4)).'</li><br>';
						   echo '<li><img height=10px src="..\web\imagens\circulo.gif"> '.str_replace('_',' ',substr($hab[2],4)).'</li>';
					   echo '<ul>';
                       echo '<div class=escudo><img height=80px src=../web/imagens/escudo.png /></div>';
                       echo '<div class=defesa>Defesa</div>';
                       echo '</div>';
                       /*echo '<div class=vantagens>';
                       echo '<caption class=fichaTitulo>Vantagens</caption>';
                       echo '<span class=linhas><hr><hr><hr><hr><hr><hr></span>';
                       echo '</div>';
                       echo '<div class=desvantagens>';
                       echo '<caption class=fichaTitulo>Desvantagens</caption>';
                       echo '<span class=linhas><hr><hr><hr><hr><hr><hr></span>';
                       echo '</div>';*/
                       echo '</form>';
					   }
      echo '</fieldset>';
               ?>
    </div>
</div>