<!DOCTYPE html>
<html>
<head>
<title>Envio de Arquivos</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>
<body>

<form action="../paginas/upload.php" method="post" enctype="multipart/form-data">
    <input type="hidden" name="MAX_FILE_SIZE" value="30000000" />
    Select image to upload:
    <input type="file" name="fileToUpload" value="" id="fileToUpload">
    <input type="submit" value="Envio de Imagem" name="submit">
</form>

</body>
</html>