<?php
   $act = $_GET['act'];
   @$x=$_GET['pag'];
   $jogador = $_COOKIE['login'];
   $variaveis=array('JOGADOR'=>'jogador','VILÃO'=>'vilao','RAÇA'=>'raca','CLASSE'=>'classe','IDADE'=>'idade','SEXO'=>'sexo','DESCRIÇÃO'=>'descricao');  
   $search->settabela('viloes');
   @$search->setvilao($_GET['vilao']);
   $dados=$dao->encontrePorVilao($search);
?>  
<div class="conteudo vilao">
   <fieldset id=seletor>
      <?php if($act == 'novo'): ?>
      <legend>CADASTRO DE VILÕES</legend>     
         <form name="formUpload" id="formUpload" class="font_1" action="../paginas/add.php?act=cadVilao" method="POST">
            <table class="vilao1">
            <?php
               foreach($variaveis as $keys => $item){
                  if($item=='sexo'){
                     echo '<tr><td align=right> '.$keys.': </td>';
                     echo '<td><input type=radio name=sexo value=M> MASCULINO';
                     echo ' <input type=radio name=sexo value=F> FEMININO</td></tr>';
                  }elseif($item=='raca'){
                     echo '<tr><td align=right> '.$keys.': </td>';
                     echo '<td><input id="mySelect" name=raca ></td></tr>';
                  }elseif($item=='classe'){
                     echo '<tr><td align=right> '.$keys.': </td>';
                        echo '<td><input name=classe id="myClasse" ></td></tr>';
                  }elseif($item=='jogador'){
                     echo "<tr><td align=\"right\"> $keys: </td><td>$login</td></tr>";
                     echo "<input type=\"hidden\" name=\"jogador\" value=\"".$login."\" size=\"40\" />";
                  }elseif($item=='descricao'){
                     echo "<tr><td align=\"right\"> $keys: </td><td><textarea name=\"".$item."\" cols=40 rows=6 ></textarea></td></tr>";
                  }elseif($item=='idade'){
                     echo "<tr><td align=\"right\"> $keys: </td><td><input type=\"number\" name=\"".$item."\"  / required></td></tr>";
                  }else{
                     echo "<tr><td align=\"right\"> $keys: </td><td><input type=\"text\" name=\"".$item."\" size=\"20\" / required></td></tr>";
                  }
               }
               //echo "<tr><td>Avatar <span class=trocaAvatar onclick=mudaImagem2()>&nbsp&nbsp&nbsp&nbsp&nbsp</span></td><td onclick=ocultar() >Noava Imagem</td>";
               echo '<input type="hidden" name="MAX_FILE_SIZE" value="3000000" />';
               echo '<tr><td></td><td onclick=esconde();><input type="file" name="arquivo" size="45" /></td></tr>'; 
            ?>
            </table>
             <span class=ocultar>Avatar <span class=trocaAvatar onclick=mudaImagem2()>&nbsp&nbsp&nbsp&nbsp&nbsp</span></span>
            <div>
               <input type="reset" value="LIMPA" class='botao botao-verde'>
               <input type="submit" value="GRAVA" class='botao botao-verde'>
            </div>
             <div class="some"><div id="aqui" class="cadVilao"></div></div>
         </form>
         <script>trocaAvatar('Trocar Avatar')</script>
      <?php elseif($act=='cad2Vilao'): ?>
      <legend>CADASTRO DE VILÕES</legend>  
         <table>
             <?php
               echo '<tr><td align=right><label>NOME: </label></td><td class=nomes2>'.$dados->getvilao().'</td><td align=right><label>IDADE: </label></td><td class=nomes2>'.$dados->getidade().'<label>anos</label></td><td align=right><label>SEXO: </label></td><td class=nomes2>'.$dados->getsexo().'</td></tr>';
               echo '<tr><td align=right><label>RAÇA: </label></td><td class=nomes2>'.$dados->getraca().'</td><td align=right><label>CLASSE: </label></td><td class=nomes2>'.$dados->getclasse().'</td></tr>';
               echo '<div class=figVilao><img height=200ppx src="../web/'.$dados->getavatar().'" /><br>';                 
                  echo '<div class=descricaoVilao>'.$dados->getDESCRICAO().'</div>';
               echo '</div>';
             ?>
         </table>
      <?php $atributos=array('Força'=>'F','Agilidade'=>'A','Inteligência'=>'I','Vontade'=>'V','Pontos de Vida'=>'PV','Pontos de Maná'=>'PM',); ?>
         <form class="font_1" id="cadastro" action="../paginas/add.php?act=cad2Vilao&vilao=<?php echo $dados->getvilao(); ?>" method="POST">
             <table class="atributo">
            <?php     
            foreach($atributos as $key => $item){
               echo '<tr><td><label>'.$key.'</label></td><td><input type=text size=2 name='.$item.' /></td></tr>';
            } 
            ?>
             </table>
            <span class="bnt">
               <input type="reset" value="LIMPA" class='botao botao-verde'>
               <input type="submit" value="GRAVA" class='botao botao-verde'>
            </span>
         </form>
         
      <?php elseif($act=='cad3Vilao'): ?>
      <legend>CADASTRO DE VILÕES</legend>  
         <table>
             <?php
               $atributos=array('Força'=>'FORCA','Agilidade'=>'AGILIDADE','Inteligência'=>'INTELIGENCIA','Vontade'=>'VONTADE','Pontos de Vida'=>'PV','Pontos de Maná'=>'PM',); 
               echo '<tr><td align=right><label>NOME: </label></td><td class=nomes2>'.$dados->getvilao().'</td><td align=right><label>IDADE: </label></td><td class=nomes2>'.$dados->getidade().'<label>anos</label></td><td align=right><label>SEXO: </label></td><td class=nomes2>'.$dados->getsexo().'</td></tr>';
               echo '<tr><td align=right><label>RAÇA: </label></td><td class=nomes2>'.$dados->getraca().'</td><td align=right><label>CLASSE: </label></td><td class=nomes2>'.$dados->getclasse().'</td></tr>'; 
               echo '<tr><th>Atributos</th></tr>';
               foreach($atributos as $key => $item){
                  $get='get'.$item;
                  echo '<tr><td align=right colspan=2><label>'.strtoupper($key).': </label></td><td class=nomes2>'.$dados->$get().'</td></tr>';
               } 
               echo '<div class=figVilao><img height=200ppx src="../web/'.$dados->getavatar().'" /><br>';                 
                  echo '<div class=textoVilao>'.$dados->getDESCRICAO().'</div>';
               echo '</div>';
             ?>
         </table>     
      <?php elseif($act=='lista'): ?>
      <?php  
         $y=$x+2;
             if($x==0){ 
                $class='class="disabled"';
             }else{
                $class='title=RECUAR';
             }
           @$z = $_GET['z'];
           if(!$z){
              $z=0;
           } 
         $search->settabela('viloes');
         $dados=$dao->encontrePorVilao($search);
         if(isset($dados)){
            $ids=array();
            foreach($dados as $item){
               $ids[]= $item->getid();
            }      
            echo '<div class=paginacaoVilao>';
               echo '<span class=pag >Páginas ';
               echo ($x)+1 .' de ';
               echo ceil(count($dados)).'</span>';
            echo '</div>';
            if(($x)+1 == ceil(count($dados)) || count($dados) == 0){
               $class2='class=disabled';
            }else{
               $class2='title="AVANÇAR"';
            }
         }
         if(!isset($class2)){
            $class2=null;
         }
         echo '<legend class=listaVilao><a href='.Utils::createLink('viloes',array('act'=>'lista','jogador'=>''.$jogador.'','pag'=>$x-1,'z'=>$z-1)).' '.$class.' ><img class=seta height=25px src=imagens/esquerda.png /> </a> LISTA DE VILÕES <a href='.Utils::createLink('viloes',array('act'=>'lista','pag'=>$x+1,'jogador'=>''.$jogador.'','contador'=>count($dados),'z'=>$z+1)).' '.$class2.'> <img class=seta height=25px src=imagens/direita.png /> </a></legend>';
      ?>
         <table>
             <?php
               $atributos=array('Força'=>'FORCA','Agilidade'=>'AGILIDADE','Inteligência'=>'INTELIGENCIA','Vontade'=>'VONTADE','Pontos de Vida'=>'PV','Pontos de Maná'=>'PM');
             if(isset($dados)){
               foreach($dados as $dado){
                  if($dado->getid() == $ids[$z]){
                 echo '<tr><td align=right><label>NOME: </label></td><td class=nomes2>'.$dado->getvilao().'</td><td align=right><label>IDADE: </label></td><td class=nomes2>'.$dado->getidade().'<label>anos</label></td><td align=right><label>SEXO: </label></td><td class=nomes2>'.$dado->getsexo().'</td></tr>';
                 echo '<tr><td align=right><label>RAÇA: </label></td><td class=nomes2>'.$dado->getraca().'</td><td align=right><label>CLASSE: </label></td><td class=nomes2>'.$dado->getclasse().'</td></tr>'; 
                 echo '<tr><th>Atributos</th></tr>';
                 foreach($atributos as $key => $item){
                    $get='get'.$item;
                    echo '<tr><td align=right><label>'.strtoupper($key).': </label></td><td class=nomes2>'.$dado->$get().'</td></tr>';
                 } 
                 echo '<div class=figVilao><img height=200ppx src="../web/'.$dado->getavatar().'" /><br>';                 
                    echo '<div class=textoVilao>'.$dado->getDESCRICAO().'</div>';
                 echo '</div>';
                 break;
                  }
               }
             }else{
                echo 'Não existe nenhum vilão cadastrado';
             }
             ?>
         </table>
      <?php endif ?>
   </fieldset>
</div>
